#include <stdint.h>
#include <stdio.h>
#include "weights.h" // Auto-generated by Python

// --- Coprocessor MMIO Map ---
#define COP_BASE       0xC0000000
volatile uint32_t* COP_START      = (uint32_t*)(COP_BASE + 0x00);
volatile uint32_t* COP_STATUS     = (uint32_t*)(COP_BASE + 0x04);
volatile uint32_t* COP_IN_BASE    = (uint32_t*)(COP_BASE + 0x08);
volatile uint32_t* COP_WT_BASE    = (uint32_t*)(COP_BASE + 0x0C);
volatile uint32_t* COP_OUT_BASE   = (uint32_t*)(COP_BASE + 0x10);
volatile uint32_t* COP_LAYER_ROWS = (uint32_t*)(COP_BASE + 0x14);
volatile uint32_t* COP_LAYER_COLS = (uint32_t*)(COP_BASE + 0x18);
volatile uint32_t* COP_BIAS_BASE  = (uint32_t*)(COP_BASE + 0x1C);
volatile uint32_t* COP_CYCLE_CNT  = (uint32_t*)(COP_BASE + 0x20);

// BRAM Pointers
volatile int8_t* INPUT_BRAM  = (int8_t*)(0xC1000000); 
volatile int8_t* WEIGHT_BRAM = (int8_t*)(0xC2000000);
volatile int32_t* OUTPUT_BRAM = (int32_t*)(0xC3000000);
volatile int32_t* BIAS_BRAM   = (int32_t*)(0xC4000000);

#define INPUT_DIM 784
#define L1_NEURONS 128

int main() {
    printf("Loading Layer 1 Weights...\n");

    // In a real environment with the UART DMA, the input image goes straight to BRAM.
    // For this test, we'll write a dummy image from the CPU.
    for (int i = 0; i < INPUT_DIM; i++) {
        INPUT_BRAM[i] = 1; // Dummy pixel value
    }

    // Load Layer 1 weights and biases from the header file into BRAM
    // (If your FPGA init already loaded the BRAM via .mem files, you can skip this loop)
    for (int i = 0; i < (INPUT_DIM * L1_NEURONS); i++) {
        WEIGHT_BRAM[i] = W1[i];
    }
    for (int i = 0; i < L1_NEURONS; i++) {
        BIAS_BRAM[i] = b1[i];
    }

    printf("Executing Layer 1 Inference (784 -> 128)...\n");

    // Configure Coprocessor
    *COP_IN_BASE    = 0;
    *COP_WT_BASE    = 0;
    *COP_OUT_BASE   = 0;
    *COP_BIAS_BASE  = 0;
    *COP_LAYER_ROWS = L1_NEURONS;
    *COP_LAYER_COLS = INPUT_DIM;
    
    // Trigger
    *COP_START = 1; 
    
    // Safety padding
    __asm__ volatile("nop\n\tnop\n\tnop");

    // Poll
    while ((*COP_STATUS & 0x02) == 0); 

    printf("Inference Complete in %u cycles.\n", *COP_CYCLE_CNT);
    printf("First 10 output activations:\n");
    
    for (int i = 0; i < 10; i++) {
        printf("Neuron %d: %d\n", i, OUTPUT_BRAM[i]);
    }

    return 0;
}